version: '3.7'
services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"  
    restart: unless-stopped
    volumes:
      - ./logs/seq-data:/data